name: Publish packages to NuGet on release

on:
  release:
    types: [published]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run tests
      run: dotnet test --verbosity normal

    - name: Create NuGet packages
      run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/DDDBlocks/DDDBlocks/releases/tag/${{ github.event.release.tag_name }}"
   
    - name: Publish packages to NuGet
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
